name: Build
on:
  push:
    branches:
      - master
      - v*
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  single-header:
    name: Source Package
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: actions/setup-python@v1

    - name: Install requirements
      run: python -m pip install scikit-build==0.10.0

    - name: Build sdist for Python
      run: python setup.py sdist

    - name: Prepare CMake config
      run: cmake -S . -B build

    - name: Make package
      run: cmake --build build --target package_source

    - name: Copy source packages
      run: |
        mkdir -p GooFit-Source
        cp build/GooFit-*-Source.tar.gz GooFit-Source
        cp build/GooFit-*-Source.tar.gz .

    - uses: actions/upload-artifact@v1
      with:
        name: GooFit Source
        path: GooFit-Source

    - uses: actions/upload-artifact@v1
      with:
        name: Python SDist
        path: dist

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          GooFit-*-Source.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
